// Code generated by MockGen. DO NOT EDIT.
// Source: calls.go
//
// Generated by this command:
//
//	mockgen -source=calls.go -destination=../../mocks/calllister_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	llm "github.com/kazemisoroush/vault/backend/internal/llm"
	gomock "go.uber.org/mock/gomock"
)

// MockCallLister is a mock of CallLister interface.
type MockCallLister struct {
	ctrl     *gomock.Controller
	recorder *MockCallListerMockRecorder
	isgomock struct{}
}

// MockCallListerMockRecorder is the mock recorder for MockCallLister.
type MockCallListerMockRecorder struct {
	mock *MockCallLister
}

// NewMockCallLister creates a new mock instance.
func NewMockCallLister(ctrl *gomock.Controller) *MockCallLister {
	mock := &MockCallLister{ctrl: ctrl}
	mock.recorder = &MockCallListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCallLister) EXPECT() *MockCallListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockCallLister) List(ctx context.Context, limit int32) ([]llm.Call, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit)
	ret0, _ := ret[0].([]llm.Call)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCallListerMockRecorder) List(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCallLister)(nil).List), ctx, limit)
}
