// Code generated by MockGen. DO NOT EDIT.
// Source: checks.go
//
// Generated by this command:
//
//	mockgen -source=checks.go -destination=../mocks/checks_mock.go -package=mocks -mock_names=Store=MockCheckStore,Converser=MockConverser,Enqueuer=MockEnqueuer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/kazemisoroush/vault/backend/internal/domain"
	llm "github.com/kazemisoroush/vault/backend/internal/llm"
	gomock "go.uber.org/mock/gomock"
)

// MockCheckStore is a mock of Store interface.
type MockCheckStore struct {
	ctrl     *gomock.Controller
	recorder *MockCheckStoreMockRecorder
	isgomock struct{}
}

// MockCheckStoreMockRecorder is the mock recorder for MockCheckStore.
type MockCheckStoreMockRecorder struct {
	mock *MockCheckStore
}

// NewMockCheckStore creates a new mock instance.
func NewMockCheckStore(ctrl *gomock.Controller) *MockCheckStore {
	mock := &MockCheckStore{ctrl: ctrl}
	mock.recorder = &MockCheckStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckStore) EXPECT() *MockCheckStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCheckStore) Get(ctx context.Context, id string) (domain.Check, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.Check)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCheckStoreMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCheckStore)(nil).Get), ctx, id)
}

// Put mocks base method.
func (m *MockCheckStore) Put(ctx context.Context, check domain.Check) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, check)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockCheckStoreMockRecorder) Put(ctx, check any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockCheckStore)(nil).Put), ctx, check)
}

// MockConverser is a mock of Converser interface.
type MockConverser struct {
	ctrl     *gomock.Controller
	recorder *MockConverserMockRecorder
	isgomock struct{}
}

// MockConverserMockRecorder is the mock recorder for MockConverser.
type MockConverserMockRecorder struct {
	mock *MockConverser
}

// NewMockConverser creates a new mock instance.
func NewMockConverser(ctrl *gomock.Controller) *MockConverser {
	mock := &MockConverser{ctrl: ctrl}
	mock.recorder = &MockConverserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConverser) EXPECT() *MockConverserMockRecorder {
	return m.recorder
}

// Converse mocks base method.
func (m *MockConverser) Converse(ctx context.Context, conv llm.Conversation) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Converse", ctx, conv)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Converse indicates an expected call of Converse.
func (mr *MockConverserMockRecorder) Converse(ctx, conv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Converse", reflect.TypeOf((*MockConverser)(nil).Converse), ctx, conv)
}

// MockEnqueuer is a mock of Enqueuer interface.
type MockEnqueuer struct {
	ctrl     *gomock.Controller
	recorder *MockEnqueuerMockRecorder
	isgomock struct{}
}

// MockEnqueuerMockRecorder is the mock recorder for MockEnqueuer.
type MockEnqueuerMockRecorder struct {
	mock *MockEnqueuer
}

// NewMockEnqueuer creates a new mock instance.
func NewMockEnqueuer(ctrl *gomock.Controller) *MockEnqueuer {
	mock := &MockEnqueuer{ctrl: ctrl}
	mock.recorder = &MockEnqueuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnqueuer) EXPECT() *MockEnqueuerMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockEnqueuer) Enqueue(ctx context.Context, checkID, ownerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, checkID, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockEnqueuerMockRecorder) Enqueue(ctx, checkID, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockEnqueuer)(nil).Enqueue), ctx, checkID, ownerID)
}
