// Code generated by MockGen. DO NOT EDIT.
// Source: emitter.go
//
// Generated by this command:
//
//	mockgen -source=emitter.go -destination=../mocks/emitter_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	telemetry "github.com/kazemisoroush/vault/backend/internal/telemetry"
	gomock "go.uber.org/mock/gomock"
)

// MockEmitter is a mock of Emitter interface.
type MockEmitter struct {
	ctrl     *gomock.Controller
	recorder *MockEmitterMockRecorder
	isgomock struct{}
}

// MockEmitterMockRecorder is the mock recorder for MockEmitter.
type MockEmitterMockRecorder struct {
	mock *MockEmitter
}

// NewMockEmitter creates a new mock instance.
func NewMockEmitter(ctrl *gomock.Controller) *MockEmitter {
	mock := &MockEmitter{ctrl: ctrl}
	mock.recorder = &MockEmitterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmitter) EXPECT() *MockEmitterMockRecorder {
	return m.recorder
}

// Emit mocks base method.
func (m *MockEmitter) Emit(namespace string, dimensions map[string]string, metrics ...telemetry.Metric) {
	m.ctrl.T.Helper()
	varargs := []any{namespace, dimensions}
	for _, a := range metrics {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Emit", varargs...)
}

// Emit indicates an expected call of Emit.
func (mr *MockEmitterMockRecorder) Emit(namespace, dimensions any, metrics ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{namespace, dimensions}, metrics...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockEmitter)(nil).Emit), varargs...)
}
