// Code generated by MockGen. DO NOT EDIT.
// Source: index.go
//
// Generated by this command:
//
//	mockgen -source=index.go -destination=../mocks/index_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/kazemisoroush/vault/backend/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIndex is a mock of Index interface.
type MockIndex struct {
	ctrl     *gomock.Controller
	recorder *MockIndexMockRecorder
	isgomock struct{}
}

// MockIndexMockRecorder is the mock recorder for MockIndex.
type MockIndexMockRecorder struct {
	mock *MockIndex
}

// NewMockIndex creates a new mock instance.
func NewMockIndex(ctrl *gomock.Controller) *MockIndex {
	mock := &MockIndex{ctrl: ctrl}
	mock.recorder = &MockIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndex) EXPECT() *MockIndexMockRecorder {
	return m.recorder
}

// AdvanceStatus mocks base method.
func (m *MockIndex) AdvanceStatus(ctx context.Context, id, from, to string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdvanceStatus", ctx, id, from, to)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdvanceStatus indicates an expected call of AdvanceStatus.
func (mr *MockIndexMockRecorder) AdvanceStatus(ctx, id, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdvanceStatus", reflect.TypeOf((*MockIndex)(nil).AdvanceStatus), ctx, id, from, to)
}

// Delete mocks base method.
func (m *MockIndex) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIndexMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIndex)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockIndex) Get(ctx context.Context, id string) (domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIndexMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIndex)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockIndex) List(ctx context.Context, ownerID string, limit int32, cursor string) ([]domain.File, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, ownerID, limit, cursor)
	ret0, _ := ret[0].([]domain.File)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockIndexMockRecorder) List(ctx, ownerID, limit, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIndex)(nil).List), ctx, ownerID, limit, cursor)
}

// ListByStatus mocks base method.
func (m *MockIndex) ListByStatus(ctx context.Context, status string, limit int32) ([]domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStatus", ctx, status, limit)
	ret0, _ := ret[0].([]domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByStatus indicates an expected call of ListByStatus.
func (mr *MockIndexMockRecorder) ListByStatus(ctx, status, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStatus", reflect.TypeOf((*MockIndex)(nil).ListByStatus), ctx, status, limit)
}

// Put mocks base method.
func (m *MockIndex) Put(ctx context.Context, file domain.File) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockIndexMockRecorder) Put(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockIndex)(nil).Put), ctx, file)
}
