// Code generated by MockGen. DO NOT EDIT.
// Source: ingester.go
//
// Generated by this command:
//
//	mockgen -source=ingester.go -destination=../mocks/ingester_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	events "github.com/aws/aws-lambda-go/events"
	gomock "go.uber.org/mock/gomock"
)

// MockIngester is a mock of Ingester interface.
type MockIngester struct {
	ctrl     *gomock.Controller
	recorder *MockIngesterMockRecorder
	isgomock struct{}
}

// MockIngesterMockRecorder is the mock recorder for MockIngester.
type MockIngesterMockRecorder struct {
	mock *MockIngester
}

// NewMockIngester creates a new mock instance.
func NewMockIngester(ctrl *gomock.Controller) *MockIngester {
	mock := &MockIngester{ctrl: ctrl}
	mock.recorder = &MockIngesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIngester) EXPECT() *MockIngesterMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockIngester) Handle(ctx context.Context, event events.S3Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockIngesterMockRecorder) Handle(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockIngester)(nil).Handle), ctx, event)
}
