// Code generated by MockGen. DO NOT EDIT.
// Source: passagesearcher.go
//
// Generated by this command:
//
//	mockgen -source=passagesearcher.go -destination=../mocks/passagesearcher_mock.go -package=mocks -mock_names=PassageSearcher=MockPassageSearcher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	kb "github.com/kazemisoroush/vault/backend/internal/kb"
	gomock "go.uber.org/mock/gomock"
)

// MockPassageSearcher is a mock of PassageSearcher interface.
type MockPassageSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockPassageSearcherMockRecorder
	isgomock struct{}
}

// MockPassageSearcherMockRecorder is the mock recorder for MockPassageSearcher.
type MockPassageSearcherMockRecorder struct {
	mock *MockPassageSearcher
}

// NewMockPassageSearcher creates a new mock instance.
func NewMockPassageSearcher(ctrl *gomock.Controller) *MockPassageSearcher {
	mock := &MockPassageSearcher{ctrl: ctrl}
	mock.recorder = &MockPassageSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPassageSearcher) EXPECT() *MockPassageSearcherMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockPassageSearcher) Search(ctx context.Context, query string, limit int) ([]kb.Passage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, limit)
	ret0, _ := ret[0].([]kb.Passage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockPassageSearcherMockRecorder) Search(ctx, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockPassageSearcher)(nil).Search), ctx, query, limit)
}
