// Code generated by MockGen. DO NOT EDIT.
// Source: probe.go
//
// Generated by this command:
//
//	mockgen -source=probe.go -destination=../mocks/probe_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProbe is a mock of Probe interface.
type MockProbe struct {
	ctrl     *gomock.Controller
	recorder *MockProbeMockRecorder
	isgomock struct{}
}

// MockProbeMockRecorder is the mock recorder for MockProbe.
type MockProbeMockRecorder struct {
	mock *MockProbe
}

// NewMockProbe creates a new mock instance.
func NewMockProbe(ctrl *gomock.Controller) *MockProbe {
	mock := &MockProbe{ctrl: ctrl}
	mock.recorder = &MockProbeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProbe) EXPECT() *MockProbeMockRecorder {
	return m.recorder
}

// Probe mocks base method.
func (m *MockProbe) Probe(content []byte) map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Probe", content)
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// Probe indicates an expected call of Probe.
func (mr *MockProbeMockRecorder) Probe(content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Probe", reflect.TypeOf((*MockProbe)(nil).Probe), content)
}

// Supports mocks base method.
func (m *MockProbe) Supports(contentType string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Supports", contentType)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Supports indicates an expected call of Supports.
func (mr *MockProbeMockRecorder) Supports(contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Supports", reflect.TypeOf((*MockProbe)(nil).Supports), contentType)
}
