// Code generated by MockGen. DO NOT EDIT.
// Source: retriever.go
//
// Generated by this command:
//
//	mockgen -source=retriever.go -destination=../mocks/retriever_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/kazemisoroush/vault/backend/internal/domain"
	retrieve "github.com/kazemisoroush/vault/backend/internal/retrieve"
	gomock "go.uber.org/mock/gomock"
)

// MockRetriever is a mock of Retriever interface.
type MockRetriever struct {
	ctrl     *gomock.Controller
	recorder *MockRetrieverMockRecorder
	isgomock struct{}
}

// MockRetrieverMockRecorder is the mock recorder for MockRetriever.
type MockRetrieverMockRecorder struct {
	mock *MockRetriever
}

// NewMockRetriever creates a new mock instance.
func NewMockRetriever(ctrl *gomock.Controller) *MockRetriever {
	mock := &MockRetriever{ctrl: ctrl}
	mock.recorder = &MockRetrieverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRetriever) EXPECT() *MockRetrieverMockRecorder {
	return m.recorder
}

// Match mocks base method.
func (m *MockRetriever) Match(ctx context.Context, query string, files []domain.File) (retrieve.Answer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Match", ctx, query, files)
	ret0, _ := ret[0].(retrieve.Answer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Match indicates an expected call of Match.
func (mr *MockRetrieverMockRecorder) Match(ctx, query, files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Match", reflect.TypeOf((*MockRetriever)(nil).Match), ctx, query, files)
}
