// Code generated by MockGen. DO NOT EDIT.
// Source: vision.go
//
// Generated by this command:
//
//	mockgen -source=vision.go -destination=../mocks/vision_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTranscriber is a mock of Transcriber interface.
type MockTranscriber struct {
	ctrl     *gomock.Controller
	recorder *MockTranscriberMockRecorder
	isgomock struct{}
}

// MockTranscriberMockRecorder is the mock recorder for MockTranscriber.
type MockTranscriberMockRecorder struct {
	mock *MockTranscriber
}

// NewMockTranscriber creates a new mock instance.
func NewMockTranscriber(ctrl *gomock.Controller) *MockTranscriber {
	mock := &MockTranscriber{ctrl: ctrl}
	mock.recorder = &MockTranscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranscriber) EXPECT() *MockTranscriberMockRecorder {
	return m.recorder
}

// Transcribe mocks base method.
func (m *MockTranscriber) Transcribe(ctx context.Context, content []byte, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transcribe", ctx, content, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transcribe indicates an expected call of Transcribe.
func (mr *MockTranscriberMockRecorder) Transcribe(ctx, content, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transcribe", reflect.TypeOf((*MockTranscriber)(nil).Transcribe), ctx, content, contentType)
}
