// Code generated by MockGen. DO NOT EDIT.
// Source: answerer.go
//
// Generated by this command:
//
//	mockgen -source=answerer.go -destination=mock/agent_mock.go -package=agentmock
//

// Package agentmock is a generated GoMock package.
package agentmock

import (
	context "context"
	reflect "reflect"

	agent "github.com/kazemisoroush/vault/backend/internal/agent"
	llm "github.com/kazemisoroush/vault/backend/internal/llm"
	gomock "go.uber.org/mock/gomock"
)

// MockAnswerer is a mock of Answerer interface.
type MockAnswerer struct {
	ctrl     *gomock.Controller
	recorder *MockAnswererMockRecorder
	isgomock struct{}
}

// MockAnswererMockRecorder is the mock recorder for MockAnswerer.
type MockAnswererMockRecorder struct {
	mock *MockAnswerer
}

// NewMockAnswerer creates a new mock instance.
func NewMockAnswerer(ctrl *gomock.Controller) *MockAnswerer {
	mock := &MockAnswerer{ctrl: ctrl}
	mock.recorder = &MockAnswererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnswerer) EXPECT() *MockAnswererMockRecorder {
	return m.recorder
}

// Answer mocks base method.
func (m *MockAnswerer) Answer(ctx context.Context, ownerID, query string) (agent.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Answer", ctx, ownerID, query)
	ret0, _ := ret[0].(agent.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Answer indicates an expected call of Answer.
func (mr *MockAnswererMockRecorder) Answer(ctx, ownerID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Answer", reflect.TypeOf((*MockAnswerer)(nil).Answer), ctx, ownerID, query)
}

// MockConverser is a mock of Converser interface.
type MockConverser struct {
	ctrl     *gomock.Controller
	recorder *MockConverserMockRecorder
	isgomock struct{}
}

// MockConverserMockRecorder is the mock recorder for MockConverser.
type MockConverserMockRecorder struct {
	mock *MockConverser
}

// NewMockConverser creates a new mock instance.
func NewMockConverser(ctrl *gomock.Controller) *MockConverser {
	mock := &MockConverser{ctrl: ctrl}
	mock.recorder = &MockConverserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConverser) EXPECT() *MockConverserMockRecorder {
	return m.recorder
}

// Converse mocks base method.
func (m *MockConverser) Converse(ctx context.Context, c llm.Conversation) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Converse", ctx, c)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Converse indicates an expected call of Converse.
func (mr *MockConverserMockRecorder) Converse(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Converse", reflect.TypeOf((*MockConverser)(nil).Converse), ctx, c)
}
