// Code generated by MockGen. DO NOT EDIT.
// Source: knowledge.go
//
// Generated by this command:
//
//	mockgen -source=knowledge.go -destination=mock/base_mock.go -package=knowledgemock
//

// Package knowledgemock is a generated GoMock package.
package knowledgemock

import (
	context "context"
	reflect "reflect"

	domain "github.com/kazemisoroush/vault/backend/internal/domain"
	knowledge "github.com/kazemisoroush/vault/backend/internal/knowledge"
	gomock "go.uber.org/mock/gomock"
)

// MockBase is a mock of Base interface.
type MockBase struct {
	ctrl     *gomock.Controller
	recorder *MockBaseMockRecorder
	isgomock struct{}
}

// MockBaseMockRecorder is the mock recorder for MockBase.
type MockBaseMockRecorder struct {
	mock *MockBase
}

// NewMockBase creates a new mock instance.
func NewMockBase(ctrl *gomock.Controller) *MockBase {
	mock := &MockBase{ctrl: ctrl}
	mock.recorder = &MockBaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBase) EXPECT() *MockBaseMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockBase) Fetch(ctx context.Context, ownerID, id string) (knowledge.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, ownerID, id)
	ret0, _ := ret[0].(knowledge.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockBaseMockRecorder) Fetch(ctx, ownerID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockBase)(nil).Fetch), ctx, ownerID, id)
}

// Query mocks base method.
func (m *MockBase) Query(ctx context.Context, ownerID string, filter knowledge.Filter) ([]domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, ownerID, filter)
	ret0, _ := ret[0].([]domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockBaseMockRecorder) Query(ctx, ownerID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockBase)(nil).Query), ctx, ownerID, filter)
}

// Search mocks base method.
func (m *MockBase) Search(ctx context.Context, ownerID, query string, filter knowledge.Filter, topK int) ([]domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, ownerID, query, filter, topK)
	ret0, _ := ret[0].([]domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockBaseMockRecorder) Search(ctx, ownerID, query, filter, topK any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockBase)(nil).Search), ctx, ownerID, query, filter, topK)
}
