/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List file records. */
        get: operations["listFiles"];
        put?: never;
        /** Register a file and get a presigned upload URL. */
        post: operations["dropFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get one file record and a presigned download URL. */
        get: operations["getFile"];
        put?: never;
        post?: never;
        /** Delete the file bytes and the record. */
        delete: operations["deleteFile"];
        options?: never;
        head?: never;
        /** Update the name or the free-form metadata. */
        patch: operations["updateFile"];
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Find files matching a natural-language query. */
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify pasted text against the owner's stored documents.
         * @description Splits the text into atomic claims, matches each claim to a supporting span in the owner's files, and verifies every verbatim span in code, character for character, against the file's stored text. The pipeline runs asynchronously; poll the check by id.
         */
        post: operations["createCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one check with its claims and verdicts. */
        get: operations["getCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent LLM calls, the trace of what the model did. */
        get: operations["listCalls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/time-to-file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report the client-measured time from asking to opening a file. */
        post: operations["reportTimeToFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        File: {
            id: string;
            name: string;
            contentType: string;
            /** Format: int64 */
            size: number;
            /**
             * @description Ingestion lifecycle. A dropped file is pending while it is staged, landed once it is stored and queued for the Knowledge Base, ingested once the Knowledge Base has indexed it and it is searchable, or failed on a terminal error.
             * @enum {string}
             */
            status: "pending" | "landed" | "ingested" | "failed";
            /** @description Free-form key-value metadata. No fixed keys, no enums. */
            meta?: {
                [key: string]: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateFileRequest: {
            name: string;
            contentType: string;
            /** Format: int64 */
            size?: number;
            meta?: {
                [key: string]: string;
            };
        };
        CreateFileResponse: {
            file: components["schemas"]["File"];
            uploadUrl: string;
        };
        GetFileResponse: {
            file: components["schemas"]["File"];
            downloadUrl: string;
        };
        ListFilesResponse: {
            files: components["schemas"]["File"][];
            cursor?: string;
        };
        UpdateFileRequest: {
            name?: string;
            meta?: {
                [key: string]: string;
            };
        };
        AskRequest: {
            query: string;
        };
        TimeToFileRequest: {
            ms: number;
        };
        AskResult: {
            file: components["schemas"]["File"];
            downloadUrl: string;
        };
        AskResponse: {
            /** @description A short human-readable answer drawn from the matched files, empty when there is none. */
            answer?: string;
            results: components["schemas"]["AskResult"][];
        };
        LlmCall: {
            op: string;
            model: string;
            prompt?: string;
            reply?: string;
            /** Format: int64 */
            inputTokens: number;
            /** Format: int64 */
            outputTokens: number;
            /** Format: int64 */
            latencyMs: number;
            ok: boolean;
            error?: string;
            /** Format: date-time */
            createdAt: string;
        };
        CallsResponse: {
            calls: components["schemas"]["LlmCall"][];
        };
        CreateCheckRequest: {
            /** @description The text to verify, roughly a pasted page or two. */
            text: string;
        };
        /** @description One passage in one of the owner's files that bears on a claim. Every reference passed the existence gate: code re-read the stored text at the offsets and matched spanText character for character before it was persisted. */
        Reference: {
            fileId: string;
            fileName: string;
            /** @description The passage, exactly as it appears in the file's stored text. */
            spanText: string;
            /** @description UTF-8 byte offset of the span in the file's stored text, located by code. Byte, not character: a JavaScript client must slice encoded bytes (TextEncoder), or locate spanText directly, rather than indexing the string by these numbers. */
            start: number;
            end: number;
            /**
             * @description How the passage bears on the claim, as judged by the model. Verbatim additionally survived a code-level claim-span comparison; a missing contradicts reference never certifies that no contradiction exists.
             * @enum {string}
             */
            relation: "verbatim" | "paraphrase" | "contradicts";
        };
        Claim: {
            text: string;
            /** @description UTF-8 byte offset of the claim in the check's own text. Byte, not character; see Reference.start for how a JavaScript client should use it. */
            start: number;
            end: number;
            /**
             * @description Verified means a reference restates the claim and code confirmed it character for character. Disputed outranks verified: the record holds contradicting evidence, and both sides are in references. Review means reworded support awaits a human. Unsupported means no supporting span was confirmed, whether the search came back empty or the model's proposals were discarded by the gate; silence, not falsehood.
             * @enum {string}
             */
            verdict: "verified" | "disputed" | "review" | "unsupported";
            references?: components["schemas"]["Reference"][];
        };
        Check: {
            id: string;
            text: string;
            /** @enum {string} */
            status: "pending" | "running" | "done" | "failed";
            claims?: components["schemas"]["Claim"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Error: {
            error: string;
        };
    };
    responses: {
        /** @description The request is invalid. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The file does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listFiles: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of file records. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListFilesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    dropFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFileRequest"];
            };
        };
        responses: {
            /** @description File record created. PUT the bytes to uploadUrl. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateFileResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File record with download URL. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetFileResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFileRequest"];
            };
        };
        responses: {
            /** @description Updated file record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["File"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    ask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Matching files, most relevant first, each with a download URL. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckRequest"];
            };
        };
        responses: {
            /** @description Check accepted and queued. Poll GET /checks/{id} for verdicts. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Check"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getCheck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The check, with claims once the pipeline has run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Check"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listCalls: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent LLM calls, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    reportTimeToFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeToFileRequest"];
            };
        };
        responses: {
            /** @description Metric recorded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
