/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List file records. */
        get: operations["listFiles"];
        put?: never;
        /** Register a file and get a presigned upload URL. */
        post: operations["dropFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get one file record and a presigned download URL. */
        get: operations["getFile"];
        put?: never;
        post?: never;
        /** Delete the file bytes and the record. */
        delete: operations["deleteFile"];
        options?: never;
        head?: never;
        /** Update the name or the free-form metadata. */
        patch: operations["updateFile"];
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Find files matching a natural-language query. */
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent LLM calls, the trace of what the model did. */
        get: operations["listCalls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        File: {
            id: string;
            name: string;
            contentType: string;
            /** Format: int64 */
            size: number;
            /**
             * @description Extraction lifecycle. A dropped file is pending until the extractor fills its metadata, then ready, or failed if the extractor errored.
             * @enum {string}
             */
            status: "pending" | "ready" | "failed";
            /** @description Free-form key-value metadata. No fixed keys, no enums. */
            meta?: {
                [key: string]: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateFileRequest: {
            name: string;
            contentType: string;
            /** Format: int64 */
            size?: number;
            meta?: {
                [key: string]: string;
            };
        };
        CreateFileResponse: {
            file: components["schemas"]["File"];
            uploadUrl: string;
        };
        GetFileResponse: {
            file: components["schemas"]["File"];
            downloadUrl: string;
        };
        ListFilesResponse: {
            files: components["schemas"]["File"][];
            cursor?: string;
        };
        UpdateFileRequest: {
            name?: string;
            meta?: {
                [key: string]: string;
            };
        };
        AskRequest: {
            query: string;
        };
        AskResult: {
            file: components["schemas"]["File"];
            downloadUrl: string;
        };
        AskResponse: {
            results: components["schemas"]["AskResult"][];
        };
        LlmCall: {
            op: string;
            model: string;
            prompt?: string;
            reply?: string;
            /** Format: int64 */
            inputTokens: number;
            /** Format: int64 */
            outputTokens: number;
            /** Format: int64 */
            latencyMs: number;
            ok: boolean;
            error?: string;
            /** Format: date-time */
            createdAt: string;
        };
        CallsResponse: {
            calls: components["schemas"]["LlmCall"][];
        };
        Error: {
            error: string;
        };
    };
    responses: {
        /** @description The request is invalid. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The file does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listFiles: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of file records. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListFilesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    dropFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFileRequest"];
            };
        };
        responses: {
            /** @description File record created. PUT the bytes to uploadUrl. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateFileResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File record with download URL. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetFileResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFileRequest"];
            };
        };
        responses: {
            /** @description Updated file record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["File"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    ask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Matching files, most relevant first, each with a download URL. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listCalls: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent LLM calls, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
